FROM ruby:3.1.2-buster

ARG DIR=/src
ENV LANG C.UTF-8
ENV BUNDLER_VERSION 2.3.13

RUN apt-get update -qq \
    && apt-get install --no-install-recommends -y \
    autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libcurl4-openssl-dev libxml2-dev libvips-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN gem update --system \
    && gem install bundler -v $BUNDLER_VERSION

RUN mkdir ${DIR}
WORKDIR ${DIR}

RUN useradd -m --shell /bin/bash --uid 1000 ruby
USER ruby

ENV EDITOR vim
ENV BUNDLE_PATH vendor/bundle

RUN bundle config --global retry 5 \
    && bundle config --global path ${BUNDLE_PATH}
